# Configuration for probot-auto-merge - https://github.com/bobvanderlinden/probot-auto-merge

updateBranch: false
deleteBranchAfterMerge: true
mergeMethod: rebase

minApprovals:
  COLLABORATOR: 0
maxRequestedChanges:
  NONE: 0
blockingLabels:
- WIP
- Blocked

rules:
- minApprovals:
    OWNER: 1
- requiredLabels:
  - Automerge
