env:
  global:
    - PATH=$HOME/.yarn/bin:$PATH
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
sudo: false
language: node_js
node_js:
  - "6"
  - "8"
cache: yarn
script: yarn test:ci
notifications:
   email: false
